#!/bin/bash
set -e

module load samtools
module load plink/1.9.0-beta4.4

bcftools norm -m-any --check-ref w -f hg38.fa POST_261.vcf | bcftools annotate -x ID -I +'%CHROM:%POS:%REF:%ALT' | bcftools norm -Ob --rm-dup both > POST_261.bcf
bcftools index POST_261.bcf

plink --noweb --bcf POST_261.bcf --keep-allele-order --vcf-idspace-to _ --const-fid --allow-extra-chr 0 --split-x b37 no-fail --make-bed --memory 240000 --out POST_261.genotypes
plink --bfile POST_261.genotypes --indiv-sort natural --make-bed --out POST_261.genotypes



mkdir Pruned_261_maf20
plink --noweb --bfile POST_261.genotypes --maf 0.10 --indep 50 5 1.5 --out Pruned_261_maf20/POST_261.genotypes
plink --noweb --bfile POST_261.genotypes --extract Pruned_261_maf20/POST_261.genotypes.prune.in --make-bed --out Pruned_261_maf20/POST_261.genotypes

#run the remaining steps in sinteractive in /data/hardyra:

find . -name "*.bim" | grep -e "Pruned_261_maf20" > POST_261_SNP_ForMerge.list
sed -i 's/.bim//g' POST_261_SNP_ForMerge.list
plink --merge-list POST_261_SNP_ForMerge.list --out POST_261_maf20

## merge experimental files and chromosomes 

plink --bfile Merged1KG_maf20 --extract POST_261_maf20.bim --allow-extra-chr 0 --make-bed --out Merged1KG_maf20.matched
plink --bfile POST_261_maf20 --bmerge Merged1KG_maf20.matched.bed Merged1KG_maf20.matched.bim Merged1KG_maf20.matched.fam --make-bed --out POST_261_Merged1KG_maf20.matched.merged   

#Create MDS
plink --bfile POST_261_Merged1KG_maf20.matched.merged --genome --threads 10 --out POST_261_Merged1KG_maf20.matched.merged
plink --bfile POST_261_Merged1KG_maf20.matched.merged --cluster --mds-plot 6 --out POST_261_Merged1KG_maf20.matched.merged

#Create PCA
plink --bfile POST_261_Merged1KG_maf20.matched.merged --pca
mv plink.eigenvec POST_261_Merged1KG_maf20.matched.merged.eigenvec

scp hardyra@helix.nih.gov:/data/hardyra/POST_261_Merged1KG_maf20.matched.merged.mds Desktop/
scp hardyra@helix.nih.gov:/data/hardyra/ POST_261_Merged1KG_maf20.matched.merged.eigenvec Desktop/


plink \
--bfile  POST_261_filter_maf10 \
--exclude POST_261_filter_maf10.ac_gt_snps \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_filter_maf10.ac_gt_snps

plink \
--bfile  Merged1KG_maf10 \
--exclude Merged1KG_maf10.ac_gt_snps \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out Merged1KG_maf10.ac_gt_snps

plink2 \
--bfile Merged1KG_maf10.ac_gt_snps \
--rm-dup force-first \
--make-bed \
--out Merged1KG_maf10.ac_gt_snps_rmdup

plink2 \
--bfile POST_261_filter_maf10.ac_gt_snps \
--rm-dup force-first \
--set-missing-var-ids @:#\$r:\$a \
--new-id-max-allele-len 23 missing \
--make-bed \
--out POST_261_filter_maf10.ac_gt_snps.rmdup

###


awk 'BEGIN {OFS="\t"} ($5$6 == "GC" || $5$6 == "CG" || $5$6 == "AT" || $5$6 == "TA") {print $2}' \
POST_261_Merged1KG_maf10.matched.merged.bim  > POST_261_Merged1KG_maf10.matched.merged.acgt

plink \
--bfile  POST_261_Merged1KG_maf10.matched.merged \
--extract POST_261_Merged1KG_maf10.matched.merged.acgt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_Merged1KG_maf10.matched.merged.acgt


##Created a subset file to include only variants that differed by .2 allele frequency in reference and data (file = merged.txt - made in R)

#plink \
--bfile  POST_261_Merged1KG_maf10.matched.merged.acgt \
--extract merge.txt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_Merged1KG_maf10.match.subset


#plink \
--bfile POST_261_Merged1KG_maf10.match.subset \
--genome \
--threads 10 \
--out POST_261_Merged1KG_maf10.match.subset

#plink \
--bfile POST_261_Merged1KG_maf10.match.subset \
--read-genome POST_261_Merged1KG_maf10.match.subset.genome \
--cluster \
--mds-plot 6 \
--out POST_261_Merged1KG_maf10.match.subset

plink --bfile POST_261_Merged1KG_maf10.match.subset --pca
mv plink.eigenvec POST_261_Merged1KG_maf10.match.subset


## EU and CA added
plink \
--bfile Merged1KG_maf20 \
--extract POST_261_filter_EU_CA_maf10.bim \
--allow-extra-chr 0 \
--make-bed \
--out Merged1KG_POSTCA_EU.matched

plink \
--bfile POST_261_filter_EU_CA_maf10 \
--bmerge Merged1KG_POSTCA_EU.matched.bed Merged1KG_POSTCA_EU.matched.bim Merged1KG_POSTCA_EU.matched.fam \
--make-bed \
--out POST_261_EU_CA_Merged1KG_maf20.matched.merged 

awk 'BEGIN {OFS="\t"} ($5$6 == "GC" || $5$6 == "CG" || $5$6 == "AT" || $5$6 == "TA") {print $2}' \
POST_261_EU_CA_Merged1KG_maf20.matched.merged.bim  > POST_261_EU_CA_Merged1KG_maf20.matched.merged.acgt

plink \
--bfile  POST_261_EU_CA_Merged1KG_maf20.matched.merged \
--extract POST_261_EU_CA_Merged1KG_maf20.matched.merged.acgt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_EU_CA_Merged1KG_maf10.matched.merged.acgt

plink \
--bfile  POST_261_EU_CA_Merged1KG_maf10.matched.merged.acgt \
--extract subset.txt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_EU_CA_Merged1KG_maf10.subset

plink \
--bfile  POST_261_EU_CA_Merged1KG_maf10.matched.merged.acgt \
--extract subset.txt \
--genome \
--nonfounders \
--threads 8 \
--out POST_261_EU_CA_Merged1KG_maf10.subset

plink \
--bfile POST_261_EU_CA_Merged1KG_maf10.subset \
--genome \
--maf .01 \
--threads 10 \
--out POST_261_EU_CA_Merged1KG_maf10.subset


plink \
--bfile  POST_261_EU_CA_Merged1KG_maf10.subset \
--read-genome POST_261_EU_CA_Merged1KG_maf10.subset.genome \
--cluster \
--mds-plot 6 \
--out POST_261_EU_CA_Merged1KG_maf10.subset

plink --bfile POST_261_EU_CA_Merged1KG_maf10.subset --pca
mv plink.eigenvec POST_261_EU_CA_Merged1KG_maf10.subset


###

awk '{if(($5 ~ /A/ && $6 ~ /T/) || ($5 ~ /T/ && $6 ~ /A/) || ($5 ~ /C/ && $6 ~ /G/) || ($5 ~ /G/ && $6 ~ /C/)) print $2}' \
POST_261_Merged1KG_maf10.matched.merged.bim > POST_261_Merged1KG_maf10.matched.merged.acgt.txt

plink \
--bfile  POST_261_Merged1KG_maf10.matched.merged \
--exclude POST_261_Merged1KG_maf10.matched.merged.acgt.txt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_Merged1KG_maf10.matched.merged.acgt

plink --bfile POST_261_Merged1KG_maf10.matched.merged.acgt --cluster --mds-plot 6 --out POST_261_Merged1KG_maf10.matched.merged.acgt

plink --bfile POST_261_Merged1KG_maf10.matched.merged.acgt \
--geno 0.05 \
--maf 0.05 \
--make-bed \
--out POST_261_Merged1KG_maf10.matched.merged.acgt.final

plink --bfile POST_261_Merged1KG_maf10.matched.merged.acgt.final \
--geno 0.05 \
--maf 0.05 \
--max-maf .35 \
--make-bed \
--out POST_261_Merged1KG_maf10.matched.merged.acgt.final

plink \
--bfile POST_261_Merged1KG_maf10.matched.merged.acgt.final \
--genome \
--threads 10 \
--out POST_261_Merged1KG_maf10.matched.merged.acgt.final

plink \
--bfile POST_261_Merged1KG_maf10.matched.merged.acgt.final \
--read-genome POST_261_Merged1KG_maf10.matched.merged.acgt.final.genome \
--cluster \
--mds-plot 6 \
--out POST_261_Merged1KG_maf10.matched.merged.acgt.final


plink --bfile POST_261_Merged1KG_maf10.matched.merged.acgt.final --freq --out 1KG_merge_final

scp hardyra@helix.nih.gov:/data/Hanserv/DATA/Transfusion/WGS/Reference_Chromsome/POST_261_Merged1KG_maf10.matched.merged.acgt.final.mds  Desktop/


#plink --bfile Merged1KG_maf10.ac_gt_snps --list-duplicate-vars suppress-first --make-bed --out Merged1KG_maf10.ac_gt_snp.dup --memory 7000

#grep -v '^#' POST_261_filter.recode.vcf.gz | cut -f 3 | sort | uniq -d > POST_261_filter_maf10.reference.dups
#plink --bfile reference --exclude reference.dups --make-bed --out reference

#sort -u Merged1KG_maf10.ac_gt_snps.bim > Merged1KG_maf10.ac_gt_snps.ac_gt_snps.duplicates-removed.bim
