#!/bin/bash
set -e

module load samtools
module load plink/1.9.0-beta4.4

## merge experimental files and chromosomes 

# Extract SNPs common to both FILE1 and FILE2
awk '{print $1,$2,$4}' \
POST_261_filter_EU_CA_NA_maf20_update.bim | \
sort \
> POST_261_filter_EU_CA_NA_maf20_comm1.txt
# 104053 SNPs

awk '{print $1,$2,$4}' \
Merged1KG_maf20.bim | \
sort \
> Merged1KG_maf20_comm1.txt
# 439347 SNPs

comm -12 \
POST_261_filter_EU_CA_NA_maf20_omm1.txt \
Merged1KG_maf20_comm1.txt | \
awk '{print $2}' \
> MatchSNPs.txt
#1769 SNPs


# Extract common SNPs from FILE1 and FILE2
plink --bfile POST_261_filter_EU_CA_NA_maf20_update \
--extract MatchSNPs.txt \
--make-bed \
--out POST_261_filter_EU_CA_NA_maf20_MatchSNPs
# 1769 variants and 434 people pass filters and QC.

plink --bfile Merged1KG_maf20 \
--extract MatchSNPs.txt \
--make-bed \
--out Merged1KG_maf20_MatchSNPs
# 1769 variants and 3202 people pass filters and QC.

plink --bfile POST_261_filter_EU_CA_NA_maf20_MatchSNPs \
--bmerge Merged1KG_maf20_MatchSNPs.bed \
Merged1KG_maf20_MatchSNPs.bim \
Merged1KG_maf20_MatchSNPs.fam \
--make-bed \
--out POST_261_filter_EU_CA_NA_1KG








# create allfiles.txt for merging files to include 1000 Genome and EU_CA_NA information
plink --bfile Merged1KG_maf10 --extract POST_261_filter_MatchSNPs.bim --allow-extra-chr 0 --make-bed --out Merged1KG_maf10.matched
plink --bfile POST_261_filter_MatchSNPs --merge-list allfiles.txt --make-bed --out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged


plink --bfile POST_261_filter_MatchSNPs --bmerge Merged1KG_maf10.matched.bed Merged1KG_maf10.matched.bim Merged1KG_maf10.matched.fam --make-bed --out POST_261_1KG_maf10.matched.merged

#remove acgt
awk '{if(($5 ~ /A/ && $6 ~ /T/) || ($5 ~ /T/ && $6 ~ /A/) || ($5 ~ /C/ && $6 ~ /G/) || ($5 ~ /G/ && $6 ~ /C/)) print $2}' \
POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.bim \
> POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt

plink \
--bfile  POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged \
--extract POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.noacgt

plink --bfile POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.noacgt \
--maf 0.05 \
--make-bed \
--out POST_261__EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final

plink --bfile POST_261__EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final \
--geno 0.2 \
--maf 0.05 \
--max-maf .35 \
--make-bed \
--out POST_261__EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final

plink \
--bfile POST_261__EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final \
--genome \
--nonfounders \
--maf 0.05 \
--threads 10 \
--out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final.g

plink \
--bfile POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.noacgt \
--read-genome POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final.genome \
--cluster \
--mds-plot 6 \
--out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final

plink --bfile POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final --freq --out 1KG_merge_final


scp hardyra@helix.nih.gov:/data/Hanserv/DATA/Transfusion/WGS/Reference_Chromsome/POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final.mds  Desktop/



