#!/bin/bash
set -e

module load samtools
module load plink/1.9.0-beta4.4

## merge experimental files and chromosomes 
# create allfiles.txt for merging files to include 1000 Genome and EU_CA_NA information
plink --bfile Merged1KG_maf10 --extract POST_261_filter_MatchSNPs.bim --allow-extra-chr 0 --make-bed --out Merged1KG_maf10.matched
plink --bfile POST_261_filter_MatchSNPs --merge-list allfiles.txt --make-bed --out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged

#remove acgt
awk '{if(($5 ~ /A/ && $6 ~ /T/) || ($5 ~ /T/ && $6 ~ /A/) || ($5 ~ /C/ && $6 ~ /G/) || ($5 ~ /G/ && $6 ~ /C/)) print $2}' \
POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.bim \
> POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt

plink \
--bfile  POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged \
--extract POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt \
--allow-extra-chr 0 \
--make-bed \
--threads 8 \
--out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.noacgt

plink --bfile POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.noacgt \
--maf 0.05 \
--make-bed \
--out POST_261__EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final

plink \
--bfile POST_261__EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final \
--genome \
--threads 10 \
--out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final

plink \
--bfile POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.noacgt \
--read-genome POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final.genome \
--cluster \
--mds-plot 6 \
--out POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final

scp hardyra@helix.nih.gov:/data/Hanserv/DATA/Transfusion/WGS/Reference_Chromsome/POST_261_EU_CA_NA_Merged1KG_maf10.matched.merged.acgt.final.mds  Desktop/



